# frozen_string_literal: true

tasks = [
  'IRS Non-Profit Tax Extempt Organizations',
  'Alabama Business Licenses',
  'Alaska Business Licenses',
  'Minnesota Business Licenses (dup)',
  'Michigan Business Licenses',
  'CDC excess deaths',
  'Kentucky Business Licenses',
  'Dallas Police Incidents',
  'SBA EIDL Data',
  'SBA EIDL Advance Data',
  'SBA Paycheck Protection Program Data',
  'Dallas Police Officer Involved Shootings',
  'Dallas Police Arrests',
  'Dallas Police Active Calls',
  'Dallas County Elections by PCT',
  'CDC Weekly Counts of Deaths by State and Select Causes',
  'CDC Weekly counts of deaths by jurisdiction and age group',
  'CDC Weekly counts of death by jurisdiction and cause of death',
  'CDC Weekly counts of deaths by jurisdiction and race and Hispanic origin',
  'Florida Professional Licenses',
  'Pima County, Arizona Delinquent Property Taxes',
  'IL Flu weekly reports',
  'San Diego, California Tax Delinquent Properties for sale',
  'Dallas Vendor Payments',
  'Number of COVID Specimens Tested and Percent Positive',
  'Massachusetts corporations',
  'Mississippi business licenses',
  'Missouri Corporations',
  'RPC Refugee admissions reports',
  'RPC refugee arrivals by admission category',
  'COVID-19 Vaccination',
  'North Dakota Business Licenses ',
  'Harris County Delinquent Tax Sale Properties',
  'Rhode Island Business Licenses',
  'Idaho Business Licenses',
  'US Patents',
  'US Patents Activities',
  'Chicago public schools supplier payments',
  'WI School Staff Report',
  'Delaware Business Licenses',
  'USDA Integrity Scrape',
  'Hawaii Business Licenses',
  'Kansas Campaign Finance',
  'Illinois Business Licenses',
  'Kansas Business Entities',
  'Utah Business Licenses',
  'Vermont Business Licenses',
  'Michigan Eastern District Court Case (51)',
  'Michigan Western District Court Case (50)',
  'mm_housing_vacancies_and_homeownerships',
  'mm_manufacturing_and_trade_inventories_and_sales',
  'New Jersey District Court Case (7)',
  'Supreme Court of Georgia Case (11)',
  'Ohio Southern District Court Case (36)',
  'Georgia Northern District Court Case (14)',
  'District Court for the Middle District of Georgia (15)',
  'VAERS Data',
  'District Court for the Eastern District of New York (25)',
  'District Court for the Western District of New York (26)',
  'USTA Rankings',
  'CTCL_municipalities',
  'Gun Violence Archive Daily',
  'Gun Violence Archive Yearly',
  'College Mandatory Vaccinations',
  'Franklin County Court Case (38, 61 and 62)',
  'Hamilton County Court Case (40)',
  'Greenville County Circuit Court (32)',
  'District Court for the District of Columbia Case (28)',
  'District Court for the District of Maryland (55)',
  'Iowa State Employee Salaries',
  'Davidson County Court (47)',
  'EinPressWire (Press Releases)',
  'PR.com (Press Releases)',
  'PRLOG (Press Releases)',
  'Building Permits by County',
  'AntifaWatch',
  'Chicago Police Department Crime Statistics',
  'Investment News and Research Project',
  'mm_monthly_retail_trade_and_food_services',
  'mm_new_residential_construction',
  'il_parole_population_date_scrape',
  'il_prison_population_data_scrape',
  'SBA PPP Loans up to $150k',
  'HEERF relief funds',
  'IRS Migrations by County',
  'quarterly_summary_of_state_and_local_taxes',
  'quarterly_survey_of_public_pensions',
  'Iowa food assistance',
  'New York City Crime Statistics',
  'Pledge to Teach the Truth',
  'Ohio State Employee Salaries',
  'Los Angeles Crime Statistics',
  'US Dept of Health and Human Services',
  'US Dept of Commerce',
  'US Securities and Exchange Commission',
  'VA Office of Inspector General',
  'US Dept of Transportation',
  'Nuclear Regulatory Commission',
  'Federal Communications Commission'
]

statuses = [
  'raw',
  'to do',
  'in progress',
  'testing',
  'on checking',
  'done'
]

statuses.each { |s| Status.find_or_create_by(name: s) }
tasks.each { |name| Task.find_or_create_by(name: name, status: Status.order('RAND()').first) }
